
modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
modId="thedigimod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Digimod" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="The ModderG" #optional
description='''
This is a long form description of the mod. You can write whatever you want here

Have some lorem ipsum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
'''
[[dependencies.thedigimod]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.thedigimod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
